name: Android CI

on:
  push:
    branches: [ "master", "release/**", "feature/**", "bugfix/**", "hotfix/**" ]
  pull_request:
    branches: [ "master", "release/**", "feature/**", "bugfix/**", "hotfix/**" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Run analyze code
      run: ./gradlew checkCodeStyle
      
    - name: Build with Gradle
      run: ./gradlew build

